### ISSUE TITLE
run embedded_watermark.py --target_blk_id=0

### ISSUE THREAD

**Issue by dsshay** [FunabikiKeisuke/dnn-watermark_pytorch#5]
I have TypeError: mean() received an invalid combination of arguments - got (NoneType, dim=int) in line w=torch.mean(embed_weight, dim=0)
I think it is because embed_weight have None value. What I should to do for drawing with  --target_blk_id=0?

**Comment by l3ickey** [comment]
I cannot answer basic questions about PyTorch.
Please try to research on your own.
